import json
from datetime import datetime

def generate_wellness_report(analysis_results):
    report = []
    report.append(f"# Weekly Wellness Report - {datetime.now().strftime('%Y-%m-%d')}\n")
    report.append("## Overview\n")
    report.append("This report provides an empathetic summary of your loved one's week, based on their activity patterns and communication logs.\n")

    # Motion Data
    motion_deviation = analysis_results["motion_deviation"]
    if motion_deviation["detected"]:
        report.append(f"\n## Motion Activity\n")
        if motion_deviation["current"] > motion_deviation["baseline"]:
            report.append(f"We noticed a positive increase in motion activity this week. Your loved one was more active than usual, which is a great sign! (Current: {motion_deviation["current"]:.0f} events, Baseline: {motion_deviation["baseline"]:.0f} events)\n")
        else:
            report.append(f"We observed a slight decrease in motion activity this week. This could be due to various reasons, and we will continue to monitor. (Current: {motion_deviation["current"]:.0f} events, Baseline: {motion_deviation["baseline"]:.0f} events)\n")
    else:
        report.append(f"\n## Motion Activity\n")
        report.append("Motion activity remained consistent with usual patterns this week. Keep up the great work!\n")

    # Sleep Data
    sleep_deviation = analysis_results["sleep_deviation"]
    if sleep_deviation["detected"]:
        report.append(f"\n## Sleep Patterns\n")
        if sleep_deviation["current"] < sleep_deviation["baseline"]:
            report.append(f"We noted a slight decrease in sleep duration this week. Ensuring restful sleep is important, and we will keep an eye on this. (Current: {sleep_deviation["current"]:.1f} hours, Baseline: {sleep_deviation["baseline"]:.1f} hours)\n")
        else:
            report.append(f"Sleep duration was slightly higher than usual this week. This could indicate a need for more rest. (Current: {sleep_deviation["current"]:.1f} hours, Baseline: {sleep_deviation["baseline"]:.1f} hours)\n")
    else:
        report.append(f"\n## Sleep Patterns\n")
        report.append("Sleep patterns were stable and consistent with usual routines this week. Good job maintaining a healthy sleep schedule!\n")

    # Call Frequency
    call_deviation = analysis_results["call_frequency_deviation"]
    if call_deviation["detected"]:
        report.append(f"\n## Communication & Social Engagement\n")
        if call_deviation["current"] < call_deviation["baseline"]:
            report.append(f"There was a slight decrease in call frequency this week. We encourage continued social engagement. (Current: {call_deviation["current"]:.0f} calls, Baseline: {call_deviation["baseline"]:.0f} calls)\n")
        else:
            report.append(f"Call frequency was higher than usual this week, indicating active social engagement. Wonderful to see! (Current: {call_deviation["current"]:.0f} calls, Baseline: {call_deviation["baseline"]:.0f} calls)\n")
    else:
        report.append(f"\n## Communication & Social Engagement\n")
        report.append("Communication patterns remained consistent with usual engagement this week. Your loved one is staying connected!\n")

    report.append("\n---\n")
    report.append("\n*This report is generated by the Aura™ AI system. For any concerns, please contact your care coordinator.*")

    return "".join(report)

if __name__ == "__main__":
    # Example usage with analysis results from aura_analysis.py
    from aura_data_ingestion import simulate_data_ingestion
    from aura_analysis import analyze_aura_data

    simulated_data = simulate_data_ingestion()
    analysis = analyze_aura_data(simulated_data)
    report = generate_wellness_report(analysis)
    print(report)
